# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e7dd5de9e855e9672261f8e950f6b2a9"
name = "avd - age verification dialog"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_metaobject_definitions,write_metaobjects,write_products,read_locales,write_files"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[shop.metafields.avd.settings]
type = "json"
name = "App Settings"

  [shop.metafields.avd.settings.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[shop.metafields.avd.checkout_banner]
type = "json"
name = "Checkout Banner"

  [shop.metafields.avd.checkout_banner.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[metaobjects.app.popups]
name = "Popups"
description = "Stores all age verification popup entries."

  [metaobjects.app.popups.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[metaobjects.app.popups.fields.popup_id]
name = "Popup ID"
type = "single_line_text_field"

[metaobjects.app.popups.fields.config]
name = "Config"
type = "json"

[metaobjects.app.translations]
name = "Translations"
description = "Summary of translated languages and their associated popups."

  [metaobjects.app.translations.access]
  admin = "merchant_read_write"
  storefront = "public_read"

[metaobjects.app.translations.fields.locale]
name = "Locale"
type = "single_line_text_field"

[metaobjects.app.translations.fields.popups]
name = "Popups"
type = "list.metaobject_reference<$app:popups>"
